# Generated by Django 4.2.30 on 2026-05-19 07:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(blank=True, default='📦', max_length=10)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=dict)),
                ('screenshots', models.JSONField(default=list)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('demo_video_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux'), ('all', 'All Platforms')], default='all', max_length=10)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('installer_file', models.FileField(blank=True, null=True, upload_to='products/installers/')),
                ('changelog', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=100)),
                ('author_company', models.CharField(blank=True, max_length=100)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_cycle', models.CharField(choices=[('one_time', 'One Time'), ('annual', 'Annual'), ('monthly', 'Monthly')], default='one_time', max_length=10)),
                ('max_users', models.PositiveIntegerField(default=1)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('features_included', models.JSONField(default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
